version: '3.7'
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    ports:
      - 1337:1337
    environment:
      - NODE_ENV=production
    build: .

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - 81:81
      - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

